# Generated by Django 2.2.7 on 2019-12-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporterName', models.CharField(max_length=60, verbose_name='first name')),
                ('reporterLast', models.CharField(max_length=60, verbose_name='last name')),
                ('reporterEmail', models.CharField(max_length=60, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleContent', models.CharField(max_length=100, verbose_name='article header')),
                ('articleReporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstTest.reporter')),
            ],
        ),
    ]
