# Generated by Django 2.2.7 on 2019-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='reporterKind',
            field=models.CharField(choices=[('writer', 'writer'), ('author', 'author')], default='select kind', max_length=10, verbose_name='reporter kind'),
        ),
    ]
