# Generated by Django 2.2.7 on 2019-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0005_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile image'),
        ),
    ]
