# Generated by Django 2.2.7 on 2019-12-18 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0007_auto_20191218_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleReporter',
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
