# Generated by Django 2.2.7 on 2019-12-19 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0008_auto_20191218_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleMain',
            field=models.CharField(max_length=3000, verbose_name='article body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
