# Generated by Django 2.2.7 on 2019-12-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0010_auto_20191219_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likerUsers',
            field=models.ManyToManyField(null=True, related_name='likerUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
